CREATE DATABASE IF NOT EXISTS test;

USE test;

CREATE TABLE IF NOT EXISTS vulnerability (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cve VARCHAR(255), -- CVE identifier (unique vulnerability ID)
    title TEXT, -- Title or short description of the vulnerability
    affected_item VARCHAR(255), -- The item or system affected by the vulnerability
    tool VARCHAR(255), -- The tool used to identify the vulnerability
    confidence INT, -- Confidence level of the vulnerability detection
    severity VARCHAR(50), -- Severity level of the vulnerability (e.g., Low, Medium, High)
    severity_score DECIMAL(3,1), -- A score from 1 to 10 to indicate the severity of the vulnerability
    host VARCHAR(255), -- Host affected by the vulnerability
    cvss DECIMAL(4,2), -- CVSS score (Common Vulnerability Scoring System)
    epss DECIMAL(4,2), -- EPSS score (Exploit Prediction Scoring System)
    summary TEXT, -- Detailed summary or description of the vulnerability
    cwe VARCHAR(255), -- CWE identifier (Common Weakness Enumeration)
    `references` TEXT, -- References or links for more information
    capec VARCHAR(255), -- CAPEC identifier (Common Attack Pattern Enumeration and Classification)
    solution TEXT, -- Solution or mitigation for the vulnerability
    impact TEXT, -- Impact or consequences of the vulnerability
    access VARCHAR(255), -- Access vector or requirements for exploiting the vulnerability
    age INT, -- Age of the vulnerability in days
    pocs TEXT, -- Proof of concepts (PoCs) or exploitation examples
    kev BOOLEAN -- Known Exploited Vulnerability (True/False)
);

-- Columns dedicated for data generated by the LLM report generation tool
CREATE TABLE IF NOT EXISTS report (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    impact_score DECIMAL(3,1), -- Impact score
    impact_score_explanation TEXT, -- Explanation of the impact score
    fix_time DECIMAL(3,1), -- Estimated fix time
    fix_time_explanation TEXT, -- Explanation of the estimated fix time
    attack_chain_impact DECIMAL(3,1), -- Impact of vulnerability in attack chain
    `description` TEXT,
    recommendations TEXT,
    other_information TEXT,
    impact TEXT,
    llm_model VARCHAR(255),
    llm_api_version VARCHAR(255),
    generated_at DATETIME,
    vulnerability_id INT(11) NOT NULL,
    CONSTRAINT `fk_report_vuln`
        FOREIGN KEY (vulnerability_id) REFERENCES vulnerability (id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS attack_chain (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    `description` TEXT,
    steps TEXT,
    recommendations TEXT,
    risk_score DECIMAL(3,1),
    risk_score_explanation TEXT
);

CREATE TABLE IF NOT EXISTS attack_chain_vulnerability (
    attack_chain_id INT,
    vulnerability_id INT,
    PRIMARY KEY(attack_chain_id, vulnerability_id),
    CONSTRAINT `fk_attack_chain_vuln`
        FOREIGN KEY(attack_chain_id) REFERENCES attack_chain(id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    CONSTRAINT `fk_vuln_attack_chain`
        FOREIGN KEY (vulnerability_id) REFERENCES vulnerability(id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
);

INSERT INTO vulnerability (title) VALUES
('foo'),
('bar'),
('baz');

INSERT INTO attack_chain (title) VALUES
('ac1'),
('ac2');

INSERT INTO attack_chain_vulnerability (attack_chain_id, vulnerability_id)
SELECT ac.id, v.id 
FROM attack_chain ac, vulnerability v 
WHERE ac.title = 'ac1' AND v.title='bar';

INSERT INTO attack_chain_vulnerability (attack_chain_id, vulnerability_id)
SELECT ac.id, v.id 
FROM attack_chain ac, vulnerability v 
WHERE ac.title = 'ac1' AND v.title='foo';


-- 2 computers op het gastennetwerk: Nmap scan report for MacBook-Pro-2 (192.168.3.121)
-- Host is up (0.11s latency).
-- Nmap scan report for iMacvanLennart (192.168.3.123)
-- Host is up (0.040s latency).
-- High 7.0
-- Username enumeration on iecetee.com/login via password reset medium 5.3
-- Short passwords on iecetee.com/login: 6 characters, high 7.3
-- CVE-2019-0708 Bluekeep critical 10.0
-- No password complexity on iecetee.com/login, medium 6.5
-- no rate limit on iecetee.com/login, high 8.5
-- Wachtwoord van gastennetwerk is 'gast' high 7.0
-- Endpoint Mymac22 is zowel met medewerker als gasten netwerk verbonden high 7.0
-- Kritieke RCE kwetsbaarheid in Mymac22 critical 9.3
-- Server met gevoelige data heeft standaardwachtwoord op medewerkersegment critical 9.0